"""empty message

Revision ID: 3935c1d396a
Revises: 
Create Date: 2015-09-02 16:38:19.278841

"""

# revision identifiers, used by Alembic.
revision = '3935c1d396a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('games')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('answer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('guesses', sa.TEXT(), nullable=True),
    sa.Column('misses', sa.TEXT(), nullable=True),
    sa.Column('board', sa.TEXT(), nullable=True),
    sa.Column('host_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###
