"""empty message

Revision ID: 55af87ac514
Revises: 3935c1d396a
Create Date: 2015-09-02 16:45:14.421193

"""

# revision identifiers, used by Alembic.
revision = '55af87ac514'
down_revision = '3935c1d396a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
